### ISSUE TITLE
Add Villagerkilling for villagers and merchant villagers

### ISSUE THREAD

**Issue by Ruymanphone** [PintaPepo/Residence#10]
**Is your feature request related to a problem? Please describe.**
Users kill my scamming villagers

**Describe the solution you'd like**
That users can't kill my villagers

**Describe alternatives you've considered**
()

**Additional context**
No additional context

If applicable, specify target Minecraft version.
1.15.2

**Comment by PintaPepo** [comment]
All merchant entities and water mobs are considered as animals now, and are protected by the animalkilling flag. This includes wandering villagers and their llamas, skeleton horses, zombie horses and many other entities that were not previously protected.
