### ISSUE TITLE
Add Waterkilling for acuatic animals

### ISSUE THREAD

**Issue by Ruymanphone** [PintaPepo/Residence#9]
**Is your feature request related to a problem? Please describe.**
The users kill my dolphins :(

**Describe the solution you'd like**
That users do not kill my aquatic friend

**Describe alternatives you've considered**
Add waterkilling flag

**Additional context**
No additional context

If applicable, specify target Minecraft version.
1.15.2

**Comment by PintaPepo** [comment]
All merchant entities and water mobs are considered as animals now, and are protected by the animalkilling flag. This includes wandering villagers and their llamas, skeleton horses, zombie horses and many other entities that were not previously protected.
